-- CloudSim PostgreSQL recreation script
--
-- Run against the target `cloudsim` database.
-- Example:
--   psql -U postgres -d cloudsim -f backend/sql/recreate_cloudsim_schema.sql
--
-- Optional maintenance flow from a different database:
--   DROP DATABASE IF EXISTS cloudsim;
--   CREATE DATABASE cloudsim;
--   \c cloudsim
--
-- This script recreates schema only. It intentionally does not seed demo users
-- or production admins. For production, use the backend admin bootstrap env
-- variables. For local demo data, use backend/scripts/recreate_seed_database.py
-- outside CLOUDSIM_ENVIRONMENT=production.

BEGIN;

DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS instances;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    hashed_password VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'User',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role_valid CHECK (role IN ('Admin', 'DevOps Engineer', 'User'))
);

CREATE INDEX ix_users_id ON users (id);
CREATE INDEX ix_users_email ON users (email);

CREATE TABLE instances (
    instance_id VARCHAR PRIMARY KEY,
    name VARCHAR NULL,
    instance_type VARCHAR NOT NULL,
    state VARCHAR NOT NULL DEFAULT 'pending',
    public_ip VARCHAR NULL,
    private_ip VARCHAR NULL,
    availability_zone VARCHAR NULL,
    launch_time TIMESTAMP WITHOUT TIME ZONE NULL,
    last_synced TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id INTEGER NULL
);

CREATE INDEX ix_instances_instance_id ON instances (instance_id);
CREATE INDEX ix_instances_state_synced ON instances (state, last_synced);

CREATE TABLE metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit VARCHAR NULL,
    recorded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    collected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_metrics_instance_id ON metrics (instance_id);
CREATE INDEX ix_metrics_instance_name_recorded ON metrics (instance_id, metric_name, recorded_at);

COMMIT;
